export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL';

export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING';
export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT';

export const CART_RESET_DATA = 'CART_RESET_DATA';

export const CART_DATA_ALL = 'CART_DATA_ALL';
export const CART_INCREASE_DATA = 'CART_INCREASE_DATA';
export const CART_DECREASE_DATA = 'CART_DECREASE_DATA';
export const CART_NEXT_STEP = 'CART_NEXT_STEP';

export const CART_DISCOUNT = 'CART_DISCOUNT';
export const CART_BACK_STEP = 'CART_BACK_STEP';
export const CART_GOTO_STEP = 'CART_GOTO_STEP';

export const ADDRESS_ADD_REQUEST = 'ADDRESS_ADD_REQUEST';
export const ADDRESS_ADD_SUCCESS = 'ADDRESS_ADD_SUCCESS';
export const ADDRESS_ADD_FAIL = 'ADDRESS_ADD_FAIL';
export const ADDRESS_ADD_RESET = 'ADDRESS_ADD_RESET';

export const CART_CHARGE_SHIPPING = 'CART_CHARGE_SHIPPING';


export const ADDRESS_LIST_REQUEST = 'ADDRESS_LIST_REQUEST';
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS';
export const ADDRESS_LIST_FAIL = 'ADDRESS_LIST_FAIL';

export const ADDRESS_DELETE_REQUEST = 'ADDRESS_DELETE_REQUEST';
export const ADDRESS_DELETE_SUCCESS = 'ADDRESS_DELETE_SUCCESS';
export const ADDRESS_DELETE_FAIL = 'ADDRESS_DELETE_FAIL';
export const ADDRESS_DELETE_RESET = 'ADDRESS_DELETE_RESET';
